CREATE TABLE `context_chunks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`filePath` varchar(1024) NOT NULL,
	`fileHash` varchar(64) NOT NULL,
	`startLine` int NOT NULL,
	`endLine` int NOT NULL,
	`startColumn` int DEFAULT 0,
	`endColumn` int,
	`chunkType` enum('function','class','interface','type','component','hook','constant','import','export','comment','block','file_summary') NOT NULL,
	`name` varchar(255),
	`parentName` varchar(255),
	`content` text NOT NULL,
	`summary` text,
	`language` varchar(50) DEFAULT 'typescript',
	`imports` json,
	`exports` json,
	`references` json,
	`embedding` json,
	`embeddingModel` varchar(64),
	`keywords` text,
	`tokenCount` int,
	`lastIndexedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `context_chunks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `context_index_status` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`status` enum('idle','indexing','completed','failed') NOT NULL DEFAULT 'idle',
	`totalFiles` int DEFAULT 0,
	`indexedFiles` int DEFAULT 0,
	`totalChunks` int DEFAULT 0,
	`lastFullIndexAt` timestamp,
	`lastIncrementalAt` timestamp,
	`indexDurationMs` int,
	`lastError` text,
	`errorCount` int DEFAULT 0,
	`excludePatterns` json,
	`includePatterns` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `context_index_status_id` PRIMARY KEY(`id`),
	CONSTRAINT `context_index_status_projectId_unique` UNIQUE(`projectId`)
);
--> statement-breakpoint
CREATE TABLE `context_queries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`query` text NOT NULL,
	`queryType` enum('keyword','semantic','hybrid') NOT NULL DEFAULT 'hybrid',
	`queryEmbedding` json,
	`resultChunkIds` json,
	`resultCount` int DEFAULT 0,
	`searchTimeMs` int,
	`tokensUsed` int,
	`relevanceFeedback` json,
	`conversationId` int,
	`agentExecutionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `context_queries_id` PRIMARY KEY(`id`)
);
