CREATE TABLE `cloned_repos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`githubRepoId` int NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`defaultBranch` varchar(255) DEFAULT 'main',
	`currentBranch` varchar(255),
	`clonePath` varchar(500),
	`cloneStatus` enum('pending','cloning','ready','error','syncing') NOT NULL DEFAULT 'pending',
	`cloneDepth` int DEFAULT 1,
	`sparseCheckoutPaths` json,
	`lastCommitSha` varchar(40),
	`lastSyncedAt` timestamp,
	`syncError` text,
	`diskSizeBytes` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cloned_repos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `github_issues` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`githubIssueNumber` int NOT NULL,
	`githubIssueId` bigint NOT NULL,
	`repoFullName` varchar(255) NOT NULL,
	`title` varchar(500) NOT NULL,
	`body` mediumtext,
	`state` enum('open','closed') NOT NULL DEFAULT 'open',
	`authorGithubId` int,
	`authorLogin` varchar(255),
	`labels` json,
	`assignees` json,
	`milestone` varchar(255),
	`linkedCardId` int,
	`syncDirection` enum('github_to_card','card_to_github','bidirectional') DEFAULT 'bidirectional',
	`lastSyncedAt` timestamp,
	`githubCreatedAt` timestamp,
	`githubUpdatedAt` timestamp,
	`githubClosedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `github_issues_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `merge_conflicts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`clonedRepoId` int NOT NULL,
	`sourceBranch` varchar(255) NOT NULL,
	`targetBranch` varchar(255) NOT NULL,
	`filePath` varchar(500) NOT NULL,
	`conflictType` enum('content','rename','delete_modify','binary') NOT NULL DEFAULT 'content',
	`baseContent` mediumtext,
	`oursContent` mediumtext,
	`theirsContent` mediumtext,
	`conflictMarkers` mediumtext,
	`resolution` mediumtext,
	`resolutionStrategy` enum('ours','theirs','manual','ai'),
	`aiSuggestion` mediumtext,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `merge_conflicts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pr_review_comments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pullRequestId` int NOT NULL,
	`githubCommentId` bigint,
	`filePath` varchar(500),
	`lineNumber` int,
	`side` enum('LEFT','RIGHT') DEFAULT 'RIGHT',
	`body` mediumtext NOT NULL,
	`authorType` enum('human','ai') NOT NULL DEFAULT 'human',
	`authorGithubId` int,
	`authorLogin` varchar(255),
	`suggestionType` enum('bug','security','performance','style','documentation','other'),
	`severity` enum('critical','warning','info'),
	`resolved` boolean DEFAULT false,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pr_review_comments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pull_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`clonedRepoId` int,
	`githubPrNumber` int NOT NULL,
	`githubPrId` bigint NOT NULL,
	`title` varchar(500) NOT NULL,
	`body` mediumtext,
	`state` enum('open','closed','merged') NOT NULL DEFAULT 'open',
	`sourceBranch` varchar(255) NOT NULL,
	`targetBranch` varchar(255) NOT NULL,
	`authorGithubId` int,
	`authorLogin` varchar(255),
	`isDraft` boolean DEFAULT false,
	`mergeable` boolean,
	`mergeableState` varchar(50),
	`additions` int DEFAULT 0,
	`deletions` int DEFAULT 0,
	`changedFiles` int DEFAULT 0,
	`aiReviewStatus` enum('pending','in_progress','completed','skipped'),
	`aiReviewSummary` mediumtext,
	`aiReviewScore` int,
	`aiReviewedAt` timestamp,
	`linkedCardId` int,
	`githubCreatedAt` timestamp,
	`githubUpdatedAt` timestamp,
	`githubMergedAt` timestamp,
	`githubClosedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pull_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webhook_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deliveryId` varchar(100) NOT NULL,
	`eventType` varchar(50) NOT NULL,
	`action` varchar(50),
	`repoFullName` varchar(255),
	`senderId` int,
	`senderLogin` varchar(255),
	`payload` json,
	`processed` boolean NOT NULL DEFAULT false,
	`processedAt` timestamp,
	`processingError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `webhook_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `webhook_events_deliveryId_unique` UNIQUE(`deliveryId`)
);
